// SPDX-FileCopyrightText: 2025-2026 Samuel Moxham
// SPDX-License-Identifier: MIT

using System;
using System.Linq;
using System.Threading.Tasks;
using Cue2.Domain.Commands;
using Cue2.Services;
using Godot;
using Godot.Collections;

namespace Cue2.Domain.Cues;

/// <summary>
/// Actions a control component can apply to a target cue.
/// </summary>
public enum ControlAction
{
    /// <summary>Start (GO) the target cue's sequence.</summary>
    Go = 0,

    /// <summary>Pause a currently playing instance of the target cue.</summary>
    Pause = 1,

    /// <summary>Stop a currently playing instance of the target cue.</summary>
    Stop = 2,

    /// <summary>Resume a paused instance of the target cue.</summary>
    Resume = 3,

    /// <summary>
    /// Start a waiting instance immediately: skip continue/follow lead-in and pre-wait.
    /// </summary>
    StartNow = 4,

    /// <summary>
    /// Fade a single target-cue property over time (volume, pan, opacity, or a routing-matrix cell).
    /// </summary>
    Fade = 5,

    /// <summary>
    /// Seek playing audio/video on the target cue (absolute time or relative offset).
    /// </summary>
    Seek = 6,

    /// <summary>
    /// Animate a canvas target layer's size and/or position.
    /// </summary>
    TranslateLayer = 7
}

/// <summary>
/// Whether a property fade targets absolute levels or offsets from the current value.
/// </summary>
public enum ControlFadeMode
{
    /// <summary>Fade to the user-specified absolute level.</summary>
    Absolute = 0,

    /// <summary>Fade by a relative offset from the current level.</summary>
    Relative = 1
}

/// <summary>
/// Which single target-cue property a <see cref="ControlAction.Fade"/> component animates.
/// One fade component controls exactly one property (use multiple fade components for parallel fades).
/// </summary>
public enum ControlFadeProperty
{
    /// <summary>Overall audio volume (dedicated audio and/or video embedded audio).</summary>
    Volume = 0,

    /// <summary>Video opacity (0–100%).</summary>
    Opacity = 1,

    /// <summary>Stereo pan/balance (−1…1) for stereo audio sources.</summary>
    Pan = 2,

    /// <summary>A single routing-matrix crosspoint level (input → output).</summary>
    RoutingMatrix = 3
}

/// <summary>
/// Cue component that, when the parent cue fires, applies a transport action
/// (GO / Pause / Stop / Resume / Start Now) to another cue identified by id or cue number.
/// </summary>
/// <remarks>
/// Target is resolved at execute time via <see cref="TargetCueId"/> first, then
/// <see cref="TargetCueNum"/> as a fallback. Multiple control components may
/// live on one cue; each is independent.
/// </remarks>
public class ControlComponent : ICueComponent
{
    /// <summary>
    /// Short UI label for a control action (header buttons, card titles, active bar).
    /// </summary>
    /// <param name="action">Control action.</param>
    /// <returns>Display string.</returns>
    public static string GetActionDisplayName(ControlAction action)
    {
        return action switch
        {
            ControlAction.Go => "GO",
            ControlAction.Pause => "Pause",
            ControlAction.Stop => "Stop",
            ControlAction.Resume => "Resume",
            ControlAction.StartNow => "Start Now",
            ControlAction.Fade => "Fade",
            ControlAction.Seek => "Seek",
            ControlAction.TranslateLayer => "Translate Layer",
            _ => action.ToString()
        };
    }

    /// <summary>
    /// True when <paramref name="name"/> is still a default placeholder the user has not customized.
    /// </summary>
    /// <param name="name">Cue name to test.</param>
    /// <returns><c>true</c> for empty / "New cue number …" / "Unnamed Cue".</returns>
    public static bool IsDefaultPlaceholderName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return true;

        string n = name.Trim();
        if (n.StartsWith("New cue number", StringComparison.OrdinalIgnoreCase))
            return true;
        if (string.Equals(n, "Unnamed Cue", StringComparison.OrdinalIgnoreCase))
            return true;

        return false;
    }

    /// <summary>
    /// True when <paramref name="name"/> matches an auto-generated control name
    /// (<c>{Action} Cue: …</c>) that the user has not manually customized away from.
    /// </summary>
    /// <param name="name">Cue name to test.</param>
    /// <returns><c>true</c> for names like <c>GO Cue: Intro</c> or <c>Pause Cue: Stinger</c>.</returns>
    public static bool IsAutoGeneratedControlName(string name)
    {
        if (string.IsNullOrWhiteSpace(name))
            return false;

        string n = name.Trim();
        foreach (ControlAction action in Enum.GetValues<ControlAction>())
        {
            string prefix = GetActionDisplayName(action) + " Cue: ";
            if (n.StartsWith(prefix, StringComparison.OrdinalIgnoreCase))
                return true;
        }

        return false;
    }

    /// <summary>
    /// True when the owner cue's name is still machine-managed and safe to overwrite on target change.
    /// </summary>
    /// <param name="name">Cue name to test.</param>
    /// <returns><c>true</c> for placeholders or auto control names.</returns>
    public static bool ShouldAutoUpdateName(string name)
    {
        return IsDefaultPlaceholderName(name) || IsAutoGeneratedControlName(name);
    }

    /// <summary>
    /// Builds the auto-name used when a control cue still has a managed name.
    /// </summary>
    /// <param name="action">Control action on this component.</param>
    /// <param name="targetName">Display name of the target cue.</param>
    /// <returns>e.g. <c>Pause Cue: Intro Music</c>.</returns>
    public static string BuildAutoName(ControlAction action, string targetName)
    {
        string actionLabel = GetActionDisplayName(action);
        string target = string.IsNullOrWhiteSpace(targetName) ? "(unnamed)" : targetName.Trim();
        return $"{actionLabel} Cue: {target}";
    }

    /// <summary>
    /// If <paramref name="owner"/> still has a managed name (placeholder or previous auto control name)
    /// and this component has a resolved target, renames the owner to <c>{Action} Cue: {TargetName}</c>.
    /// </summary>
    /// <param name="owner">Cue that owns this control component.</param>
    /// <returns><c>true</c> if the name was changed.</returns>
    /// <remarks>
    /// Only the <b>first</b> control component in list order (#1) drives auto-naming so adding
    /// further controls does not keep overwriting the cue name.
    /// Retargeting the #1 control still updates e.g. <c>GO Cue: CUE1</c> → <c>GO Cue: CUE3</c>.
    /// Manually edited names are left alone.
    /// </remarks>
    public bool TryAutoRenameOwnerCue(Cue owner)
    {
        if (owner == null)
            return false;

        // Only execution-order #1 may rename the owning cue.
        var firstControl = owner.Components?.OfType<ControlComponent>().FirstOrDefault();
        if (!ReferenceEquals(firstControl, this))
            return false;

        if (!ShouldAutoUpdateName(owner.Name))
            return false;
        if (TargetCueId < 0)
            return false;

        var target = CueList.FetchCueFromId(TargetCueId);
        if (target == null)
            return false;

        string targetName = string.IsNullOrWhiteSpace(target.Name)
            ? (string.IsNullOrWhiteSpace(target.CueNum) ? $"id {target.Id}" : $"#{target.CueNum}")
            : target.Name;

        string newName = BuildAutoName(Action, targetName);
        if (string.Equals(owner.Name, newName, StringComparison.Ordinal))
            return false;

        owner.Name = newName;
        return true;
    }

    /// <inheritdoc />
    public string Type => "Control";

    /// <summary>
    /// Transport action applied to the target when this component executes.
    /// </summary>
    /// <value>One of <see cref="ControlAction"/>.</value>
    public ControlAction Action { get; set; } = ControlAction.Go;

    /// <summary>
    /// Unique id of the target cue. <c>-1</c> means unset / unresolved.
    /// </summary>
    /// <value>Cue id, or <c>-1</c> when no target is assigned.</value>
    public int TargetCueId { get; set; } = -1;

    /// <summary>
    /// Cue number string of the target (user-facing). Kept in sync with id when resolved.
    /// </summary>
    /// <value>Cue number text, or empty when unset.</value>
    public string TargetCueNum { get; set; } = string.Empty;

    /// <summary>
    /// When true (default), Stop uses the session <c>Settings.StopFadeDuration</c> at fire time.
    /// </summary>
    /// <value><c>true</c> until the user sets a custom fade on this component.</value>
    public bool StopFadeUsesSessionDefault { get; set; } = true;

    /// <summary>
    /// Custom stop fade-out duration in seconds when not using the session default.
    /// </summary>
    /// <value>Seconds; <c>0</c> means stop immediately.</value>
    public double StopFadeDuration { get; set; }

    /// <summary>
    /// Fade-in duration in seconds applied when this control GO's the target cue.
    /// </summary>
    /// <value>Seconds; default <c>0</c> (no control fade-in; target component fades still apply).</value>
    public double GoFadeInDuration { get; set; }

    /// <summary>
    /// Duration for a <see cref="ControlAction.Fade"/> property fade (seconds).
    /// </summary>
    /// <value>Default is <c>1</c> second. <c>0</c> = snap immediately.</value>
    public double PropertyFadeDuration { get; set; } = 1.0;

    /// <summary>
    /// Absolute vs relative interpretation of fade target values.
    /// </summary>
    public ControlFadeMode FadeMode { get; set; } = ControlFadeMode.Absolute;

    /// <summary>
    /// Which single property this fade animates on the target cue.
    /// </summary>
    /// <value>Default <see cref="ControlFadeProperty.Volume"/>.</value>
    public ControlFadeProperty FadeProperty { get; set; } = ControlFadeProperty.Volume;

    /// <summary>
    /// Legacy dual-enable flag (volume). Kept for save/load migration; execution uses <see cref="FadeProperty"/>.
    /// </summary>
    public bool FadeAudioVolumeEnabled { get; set; } = true;

    /// <summary>
    /// Legacy dual-enable flag (opacity). Kept for save/load migration; execution uses <see cref="FadeProperty"/>.
    /// </summary>
    public bool FadeVideoOpacityEnabled { get; set; } = true;

    /// <summary>
    /// Level for Volume fades: absolute target dB (−60…+12 digital gain) or relative delta dB.
    /// Also used as legacy single-cell matrix level when migrating old saves.
    /// </summary>
    /// <value>Default <c>0</c> dB (unity / no change when relative).</value>
    public float FadeAudioDb { get; set; }

    /// <summary>
    /// Opacity for Fade: absolute percent (0…100) or relative delta percent.
    /// </summary>
    /// <value>Default <c>100</c> for absolute full opacity; treat as delta when relative.</value>
    public float FadeOpacityPercent { get; set; } = 100f;

    /// <summary>
    /// Pan for Fade: absolute (−1…1) or relative delta when <see cref="FadeMode"/> is Relative.
    /// </summary>
    /// <value>Default <c>0</c> (center / no relative change).</value>
    public float FadePan { get; set; }

    /// <summary>
    /// Legacy single routing-matrix input index (migrated into <see cref="FadeMatrixCellTargets"/>).
    /// </summary>
    public int FadeMatrixInputIndex { get; set; }

    /// <summary>
    /// Legacy single routing-matrix output index (migrated into <see cref="FadeMatrixCellTargets"/>).
    /// </summary>
    public int FadeMatrixOutputIndex { get; set; }

    /// <summary>
    /// Sparse set of routing-matrix cells to fade in one component.
    /// Key = packed <c>(input &lt;&lt; 16) | output</c>, value = absolute dB or relative Δ dB.
    /// </summary>
    /// <remarks>
    /// Empty means no cells are targeted (fade is a no-op for matrix). Multiple cells fade in parallel.
    /// </remarks>
    public System.Collections.Generic.Dictionary<int, float> FadeMatrixCellTargets { get; set; } = new();

    /// <summary>
    /// Packs input/output indices into a single dictionary key for <see cref="FadeMatrixCellTargets"/>.
    /// </summary>
    public static int PackMatrixCellKey(int inputIndex, int outputIndex) =>
        (inputIndex << 16) | (outputIndex & 0xFFFF);

    /// <summary>
    /// Unpacks a <see cref="PackMatrixCellKey"/> value.
    /// </summary>
    public static void UnpackMatrixCellKey(int key, out int inputIndex, out int outputIndex)
    {
        inputIndex = key >> 16;
        outputIndex = key & 0xFFFF;
    }

    /// <summary>
    /// True when this cell is included in the multi-cell matrix fade set.
    /// </summary>
    public bool HasMatrixCellTarget(int inputIndex, int outputIndex) =>
        FadeMatrixCellTargets != null &&
        FadeMatrixCellTargets.ContainsKey(PackMatrixCellKey(inputIndex, outputIndex));

    /// <summary>
    /// Gets the stored target dB for a matrix cell, if any.
    /// </summary>
    public bool TryGetMatrixCellTargetDb(int inputIndex, int outputIndex, out float db)
    {
        db = 0f;
        if (FadeMatrixCellTargets == null) return false;
        return FadeMatrixCellTargets.TryGetValue(PackMatrixCellKey(inputIndex, outputIndex), out db);
    }

    /// <summary>
    /// Adds or updates a matrix cell fade target.
    /// </summary>
    public void SetMatrixCellTarget(int inputIndex, int outputIndex, float db)
    {
        FadeMatrixCellTargets ??= new System.Collections.Generic.Dictionary<int, float>();
        FadeMatrixCellTargets[PackMatrixCellKey(inputIndex, outputIndex)] = db;
        // Keep legacy fields pointed at the most recently edited cell for old tools.
        FadeMatrixInputIndex = Math.Max(0, inputIndex);
        FadeMatrixOutputIndex = Math.Max(0, outputIndex);
        FadeAudioDb = db;
    }

    /// <summary>
    /// Removes a matrix cell from the multi-cell fade set.
    /// </summary>
    public bool RemoveMatrixCellTarget(int inputIndex, int outputIndex)
    {
        if (FadeMatrixCellTargets == null) return false;
        return FadeMatrixCellTargets.Remove(PackMatrixCellKey(inputIndex, outputIndex));
    }

    /// <summary>
    /// Clears all matrix cell fade targets.
    /// </summary>
    public void ClearMatrixCellTargets()
    {
        FadeMatrixCellTargets?.Clear();
    }

    /// <summary>
    /// Short UI label for a fade property.
    /// </summary>
    /// <param name="property">Fade property.</param>
    /// <returns>Display string.</returns>
    public static string GetFadePropertyDisplayName(ControlFadeProperty property)
    {
        return property switch
        {
            ControlFadeProperty.Volume => "Volume",
            ControlFadeProperty.Opacity => "Opacity",
            ControlFadeProperty.Pan => "Pan",
            ControlFadeProperty.RoutingMatrix => "Routing Matrix",
            _ => property.ToString()
        };
    }

    /// <summary>
    /// Absolute vs relative interpretation of <see cref="SeekTimeSeconds"/>.
    /// </summary>
    public ControlFadeMode SeekMode { get; set; } = ControlFadeMode.Absolute;

    /// <summary>
    /// Seek time in seconds: absolute media time, or relative offset when <see cref="SeekMode"/> is Relative.
    /// </summary>
    /// <value>Default <c>0</c> (start / no relative move).</value>
    public double SeekTimeSeconds { get; set; }

    /// <summary>
    /// Canvas target layer id for <see cref="ControlAction.TranslateLayer"/>. <c>-1</c> = unset.
    /// </summary>
    public int TargetLayerId { get; set; } = -1;

    /// <summary>
    /// Absolute vs relative for layer size/position translation.
    /// </summary>
    public ControlFadeMode TranslateMode { get; set; } = ControlFadeMode.Absolute;

    /// <summary>
    /// Duration of layer translate animation in seconds. <c>0</c> = instant.
    /// </summary>
    public double TranslateDuration { get; set; }

    /// <summary>When true, size is included in the translate.</summary>
    public bool TranslateSizeEnabled { get; set; } = true;

    /// <summary>When true, canvas position is included in the translate.</summary>
    public bool TranslatePositionEnabled { get; set; } = true;

    /// <summary>Size X (absolute pixels or relative delta).</summary>
    public int TranslateSizeX { get; set; }

    /// <summary>Size Y (absolute pixels or relative delta).</summary>
    public int TranslateSizeY { get; set; }

    /// <summary>Canvas position X (absolute pixels or relative delta).</summary>
    public int TranslatePosX { get; set; }

    /// <summary>Canvas position Y (absolute pixels or relative delta).</summary>
    public int TranslatePosY { get; set; }

    /// <summary>
    /// True when no target is assigned (id unset and number empty).
    /// </summary>
    public bool IsTargetAtDefault =>
        TargetCueId < 0 && string.IsNullOrWhiteSpace(TargetCueNum);

    /// <summary>
    /// True when translate duration is still at default 0 (or action is not TranslateLayer).
    /// </summary>
    public bool IsTranslateDurationAtDefault =>
        Action != ControlAction.TranslateLayer || TranslateDuration <= 1e-9;

    /// <summary>
    /// True when stop fade is still tied to the session setting (or action is not Stop).
    /// </summary>
    public bool IsStopFadeAtDefault =>
        Action != ControlAction.Stop || StopFadeUsesSessionDefault;

    /// <summary>
    /// True when GO fade-in is still at its default of zero (or action is not GO).
    /// </summary>
    public bool IsGoFadeAtDefault =>
        Action != ControlAction.Go || GoFadeInDuration <= 1e-9;

    /// <summary>
    /// True when property-fade duration is still at its default of 1s (or action is not Fade).
    /// </summary>
    public bool IsPropertyFadeDurationAtDefault =>
        Action != ControlAction.Fade || Math.Abs(PropertyFadeDuration - 1.0) < 1e-9;

    /// <summary>
    /// True when the fade/time field for the current action is at its default.
    /// </summary>
    public bool IsFadeAtDefault =>
        Action switch
        {
            ControlAction.Stop => IsStopFadeAtDefault,
            ControlAction.Go => IsGoFadeAtDefault,
            ControlAction.Fade => IsPropertyFadeDurationAtDefault,
            ControlAction.TranslateLayer => IsTranslateDurationAtDefault,
            _ => true
        };

    /// <summary>
    /// Resolves the fade duration used for a Stop action.
    /// </summary>
    /// <param name="sessionDefault">Live session stop-fade setting.</param>
    /// <returns>Non-negative seconds; <c>0</c> = immediate.</returns>
    public double ResolveStopFadeDuration(float sessionDefault)
    {
        if (StopFadeUsesSessionDefault)
            return Math.Max(0.0, sessionDefault);
        return Math.Max(0.0, StopFadeDuration);
    }

    /// <summary>
    /// Wall-clock duration this control may occupy when the parent cue fires (for shell duration
    /// and active-cue progress). Instant transport (Pause / Resume / Start Now / Seek) is 0.
    /// </summary>
    /// <param name="sessionStopFadeDefault">
    /// Session stop-fade seconds used when <see cref="StopFadeUsesSessionDefault"/> is true.
    /// </param>
    /// <returns>Non-negative seconds; <c>0</c> means instantaneous (no progress bar).</returns>
    public double GetContentDurationSeconds(float sessionStopFadeDefault = 0f)
    {
        return Action switch
        {
            ControlAction.Fade => Math.Max(0.0, PropertyFadeDuration),
            ControlAction.TranslateLayer => Math.Max(0.0, TranslateDuration),
            ControlAction.Stop => ResolveStopFadeDuration(sessionStopFadeDefault),
            ControlAction.Go => Math.Max(0.0, GoFadeInDuration),
            _ => 0.0
        };
    }

    /// <summary>
    /// True when <see cref="GetContentDurationSeconds"/> is greater than zero (progress-bar eligible).
    /// </summary>
    /// <param name="sessionStopFadeDefault">Session stop-fade for Stop actions.</param>
    public bool HasTimedProgress(float sessionStopFadeDefault = 0f) =>
        GetContentDurationSeconds(sessionStopFadeDefault) > 1e-9;

    /// <summary>
    /// Clears the target cue (id and number).
    /// </summary>
    public void ClearTarget()
    {
        TargetCueId = -1;
        TargetCueNum = string.Empty;
    }

    /// <summary>
    /// Restores stop fade to follow the session stop-fade setting.
    /// </summary>
    public void ResetStopFadeToSessionDefault()
    {
        StopFadeUsesSessionDefault = true;
        StopFadeDuration = 0;
    }

    /// <summary>
    /// Restores GO fade-in to the default of zero.
    /// </summary>
    public void ResetGoFadeInToDefault()
    {
        GoFadeInDuration = 0;
    }

    /// <summary>
    /// Restores property-fade duration to the default of 1 second.
    /// </summary>
    public void ResetPropertyFadeDurationToDefault()
    {
        PropertyFadeDuration = 1.0;
    }

    /// <summary>
    /// Restores translate duration to instant (0).
    /// </summary>
    public void ResetTranslateDurationToDefault()
    {
        TranslateDuration = 0;
    }

    /// <summary>
    /// Applies this control action to the configured target cue or layer.
    /// </summary>
    /// <param name="executor">Playback executor used for control transport actions.</param>
    /// <param name="sourceCueId">Id of the cue that owns this component (used to block self-target recursion).</param>
    /// <param name="sessionStopFadeDuration">Session default stop fade (seconds) for Stop actions.</param>
    /// <returns>A task that completes when this control action has finished applying.</returns>
    public async Task ExecuteAsync(
        CueCommandExecutor executor,
        int sourceCueId = -1,
        float sessionStopFadeDuration = 0f)
    {
        try
        {
            if (executor == null)
            {
                GD.PrintErr("ControlComponent:ExecuteAsync - Executor is null");
                return;
            }

            if (Action == ControlAction.TranslateLayer)
            {
                if (TargetLayerId < 0)
                {
                    GD.Print("ControlComponent:ExecuteAsync - No target layer for Translate Layer");
                    return;
                }

                await executor.ApplyControlComponentAsync(this, sourceCueId, sessionStopFadeDuration);
                GD.Print($"ControlComponent:ExecuteAsync - TranslateLayer → layer id {TargetLayerId}");
                return;
            }

            ResolveTargetIfNeeded();

            if (TargetCueId < 0)
            {
                GD.Print($"ControlComponent:ExecuteAsync - No valid target for {Action}");
                return;
            }

            // A cue controlling itself can recurse (especially GO / Start Now).
            // Fade on self is allowed (levels on this cue's media are fine).
            if (Action != ControlAction.Fade &&
                sourceCueId >= 0 && TargetCueId == sourceCueId)
            {
                GD.PrintErr(
                    $"ControlComponent:ExecuteAsync - Refusing {Action} on self (cue id {sourceCueId})");
                return;
            }

            // Await so the next control component in list order sees the result (e.g. GO then Start Now).
            await executor.ApplyControlComponentAsync(this, sourceCueId, sessionStopFadeDuration);
            GD.Print($"ControlComponent:ExecuteAsync - {Action} → cue id {TargetCueId}");
        }
        catch (Exception ex)
        {
            GD.PrintErr($"ControlComponent:ExecuteAsync - Failed: {ex.Message}");
        }
    }

    /// <summary>
    /// If id is unset but cue number is set (or vice versa), fill in from the live cuelist.
    /// </summary>
    public void ResolveTargetIfNeeded()
    {
        if (TargetCueId >= 0)
        {
            var byId = CueList.FetchCueFromId(TargetCueId);
            if (byId != null)
            {
                TargetCueNum = byId.CueNum ?? string.Empty;
                return;
            }
            // Stale id — fall through to number lookup.
            TargetCueId = -1;
        }

        if (string.IsNullOrWhiteSpace(TargetCueNum))
            return;

        var byNum = CueList.FetchCueFromCueNum(TargetCueNum.Trim());
        if (byNum != null)
            TargetCueId = byNum.Id;
    }

    /// <summary>
    /// Looks up the target cue's display name, or empty if unresolved.
    /// </summary>
    /// <returns>Target cue name, or empty string.</returns>
    public string GetTargetCueName()
    {
        ResolveTargetIfNeeded();
        if (TargetCueId < 0) return string.Empty;
        return CueList.FetchCueFromId(TargetCueId)?.Name ?? string.Empty;
    }

    /// <summary>
    /// True when <paramref name="cue"/> has a dedicated audio component or a video component
    /// with embedded audio enabled (<see cref="VideoComponent.HasAudio"/> + <see cref="VideoComponent.UseAudio"/>).
    /// </summary>
    public static bool CueHasFadableAudio(Cue cue)
    {
        if (cue == null) return false;
        if (cue.GetAudioComponent() != null) return true;
        return VideoHasEmbeddedAudio(cue.GetVideoComponent());
    }

    /// <summary>
    /// True when <paramref name="cue"/> has a video component (opacity can be faded).
    /// </summary>
    public static bool CueHasFadableOpacity(Cue cue) =>
        cue?.GetVideoComponent() != null;

    /// <summary>
    /// True when video has playable embedded audio that participates in volume fades.
    /// </summary>
    public static bool VideoHasEmbeddedAudio(VideoComponent video) =>
        video != null && video.HasAudio && video.UseAudio;

    /// <summary>
    /// True when the cue has stereo audio (dedicated or embedded) that can be panned.
    /// </summary>
    public static bool CueHasFadablePan(Cue cue)
    {
        if (cue == null) return false;
        var audio = cue.GetAudioComponent();
        if (audio?.Metadata != null && audio.Metadata.Channels == 2)
            return true;
        var video = cue.GetVideoComponent();
        if (VideoHasEmbeddedAudio(video) && video.Metadata != null && video.Metadata.AudioChannels == 2)
            return true;
        return false;
    }

    /// <summary>
    /// True when the cue has a routing matrix (dedicated audio and/or embedded video audio).
    /// </summary>
    public static bool CueHasFadableRouting(Cue cue)
    {
        if (cue == null) return false;
        if (HasUsableRouting(cue.GetAudioComponent()?.Routing))
            return true;
        if (VideoHasEmbeddedAudio(cue.GetVideoComponent()) &&
            HasUsableRouting(cue.GetVideoComponent()?.Routing))
            return true;
        return false;
    }

    /// <summary>
    /// True when <paramref name="routing"/> has at least one input and one output channel.
    /// </summary>
    public static bool HasUsableRouting(CuePatch routing) =>
        routing != null && routing.InputChannels > 0 && routing.OutputChannels > 0;

    /// <summary>
    /// Returns whether <paramref name="property"/> can be faded on <paramref name="cue"/>.
    /// </summary>
    public static bool CueSupportsFadeProperty(Cue cue, ControlFadeProperty property)
    {
        return property switch
        {
            ControlFadeProperty.Volume => CueHasFadableAudio(cue),
            ControlFadeProperty.Opacity => CueHasFadableOpacity(cue),
            ControlFadeProperty.Pan => CueHasFadablePan(cue),
            ControlFadeProperty.RoutingMatrix => CueHasFadableRouting(cue),
            _ => false
        };
    }

    /// <summary>
    /// Lists fade properties available on <paramref name="cue"/> (stable order for UI).
    /// </summary>
    public static System.Collections.Generic.List<ControlFadeProperty> GetAvailableFadeProperties(Cue cue)
    {
        var list = new System.Collections.Generic.List<ControlFadeProperty>(4);
        if (CueHasFadableAudio(cue)) list.Add(ControlFadeProperty.Volume);
        if (CueHasFadablePan(cue)) list.Add(ControlFadeProperty.Pan);
        if (CueHasFadableRouting(cue)) list.Add(ControlFadeProperty.RoutingMatrix);
        if (CueHasFadableOpacity(cue)) list.Add(ControlFadeProperty.Opacity);
        return list;
    }

    /// <summary>
    /// Prefer the dedicated audio routing matrix; fall back to video embedded audio routing.
    /// </summary>
    public static CuePatch GetPrimaryRouting(Cue cue)
    {
        if (cue == null) return null;
        var audioRoute = cue.GetAudioComponent()?.Routing;
        if (HasUsableRouting(audioRoute))
            return audioRoute;
        var video = cue.GetVideoComponent();
        if (VideoHasEmbeddedAudio(video) && HasUsableRouting(video.Routing))
            return video.Routing;
        return null;
    }

    /// <summary>
    /// Linear volume used for embedded video audio playback (prefers <see cref="VideoComponent.AudioVolume"/>).
    /// </summary>
    public static float GetVideoAudioLinear(VideoComponent video)
    {
        if (video == null) return 0f;
        if (video.UseAudio)
            return Cue2.Media.Audio.AudioMixMatrix.ClampComponentGainLinear(video.AudioVolume);
        return Cue2.Media.Audio.AudioMixMatrix.ClampComponentGainLinear((float)video.Volume);
    }

    /// <summary>
    /// Writes embedded video audio linear volume to the field used by playback.
    /// </summary>
    public static void SetVideoAudioLinear(VideoComponent video, float linear)
    {
        if (video == null) return;
        linear = Cue2.Media.Audio.AudioMixMatrix.ClampComponentGainLinear(linear);
        if (video.UseAudio)
            video.AudioVolume = linear;
        else
            video.Volume = linear;
    }

    /// <summary>
    /// True when <paramref name="cue"/> (or any nested child) has audio/video media that can be seeked while playing.
    /// Groups are seekable when they contain seekable descendants — parent timeline seek propagates to children.
    /// </summary>
    public static bool CueHasSeekableMedia(Cue cue)
    {
        if (cue == null) return false;
        if (cue.GetAudioComponent() != null || cue.GetVideoComponent() != null)
            return true;

        if (cue.ChildCues == null || cue.ChildCues.Count == 0)
            return false;

        foreach (int childId in cue.ChildCues)
        {
            var child = CueList.FetchCueFromId(childId);
            if (CueHasSeekableMedia(child))
                return true;
        }

        return false;
    }

    /// <summary>
    /// Serializes <see cref="FadeMatrixCellTargets"/> for save/history.
    /// </summary>
    private Godot.Collections.Array SerializeMatrixCellTargets()
    {
        var cells = new Godot.Collections.Array();
        if (FadeMatrixCellTargets == null || FadeMatrixCellTargets.Count == 0)
            return cells;

        foreach (var kvp in FadeMatrixCellTargets)
        {
            UnpackMatrixCellKey(kvp.Key, out int inIdx, out int outIdx);
            cells.Add(new Dictionary
            {
                { "In", inIdx },
                { "Out", outIdx },
                { "Db", kvp.Value }
            });
        }
        return cells;
    }

    /// <inheritdoc />
    public Dictionary GetData()
    {
        // Keep legacy single-cell fields aligned with the first multi-cell entry when present.
        if (FadeMatrixCellTargets != null && FadeMatrixCellTargets.Count > 0)
        {
            var first = FadeMatrixCellTargets.First();
            UnpackMatrixCellKey(first.Key, out int inIdx, out int outIdx);
            FadeMatrixInputIndex = inIdx;
            FadeMatrixOutputIndex = outIdx;
            FadeAudioDb = first.Value;
        }

        return new Dictionary
        {
            { "Action", (int)Action },
            { "TargetCueId", TargetCueId },
            { "TargetCueNum", TargetCueNum ?? string.Empty },
            { "StopFadeUsesSessionDefault", StopFadeUsesSessionDefault },
            { "StopFadeDuration", StopFadeDuration },
            { "GoFadeInDuration", GoFadeInDuration },
            { "PropertyFadeDuration", PropertyFadeDuration },
            { "FadeMode", (int)FadeMode },
            { "FadeProperty", (int)FadeProperty },
            // Legacy dual-enable mirrors (derived from FadeProperty) for older builds / migration.
            { "FadeAudioVolumeEnabled", FadeProperty == ControlFadeProperty.Volume },
            { "FadeVideoOpacityEnabled", FadeProperty == ControlFadeProperty.Opacity },
            { "FadeAudioDb", FadeAudioDb },
            { "FadeOpacityPercent", FadeOpacityPercent },
            { "FadePan", FadePan },
            { "FadeMatrixInputIndex", FadeMatrixInputIndex },
            { "FadeMatrixOutputIndex", FadeMatrixOutputIndex },
            { "FadeMatrixCells", SerializeMatrixCellTargets() },
            { "SeekMode", (int)SeekMode },
            { "SeekTimeSeconds", SeekTimeSeconds },
            { "TargetLayerId", TargetLayerId },
            { "TranslateMode", (int)TranslateMode },
            { "TranslateDuration", TranslateDuration },
            { "TranslateSizeEnabled", TranslateSizeEnabled },
            { "TranslatePositionEnabled", TranslatePositionEnabled },
            { "TranslateSizeX", TranslateSizeX },
            { "TranslateSizeY", TranslateSizeY },
            { "TranslatePosX", TranslatePosX },
            { "TranslatePosY", TranslatePosY }
        };
    }

    /// <inheritdoc />
    public void LoadFromData(Dictionary data)
    {
        if (data == null) return;

        if (data.TryGetValue("Action", out var actionVal))
            Action = (ControlAction)actionVal.AsInt32();

        if (data.TryGetValue("TargetCueId", out var idVal))
            TargetCueId = idVal.AsInt32();

        if (data.TryGetValue("TargetCueNum", out var numVal))
            TargetCueNum = numVal.AsString();
        else
            TargetCueNum = string.Empty;

        // Legacy saves without fade keys keep session default behaviour.
        if (data.TryGetValue("StopFadeUsesSessionDefault", out var useDefaultVal))
            StopFadeUsesSessionDefault = useDefaultVal.AsBool();
        else
            StopFadeUsesSessionDefault = !data.ContainsKey("StopFadeDuration");

        if (data.TryGetValue("StopFadeDuration", out var fadeVal))
            StopFadeDuration = fadeVal.AsDouble();
        else
            StopFadeDuration = 0;

        if (data.TryGetValue("GoFadeInDuration", out var goFadeVal))
            GoFadeInDuration = Math.Max(0.0, goFadeVal.AsDouble());
        else
            GoFadeInDuration = 0;

        if (data.TryGetValue("PropertyFadeDuration", out var propFadeVal))
            PropertyFadeDuration = Math.Max(0.0, propFadeVal.AsDouble());
        else
            PropertyFadeDuration = 1.0;

        if (data.TryGetValue("FadeMode", out var modeVal))
            FadeMode = (ControlFadeMode)modeVal.AsInt32();
        else
            FadeMode = ControlFadeMode.Absolute;

        if (data.TryGetValue("FadeAudioVolumeEnabled", out var audEn))
            FadeAudioVolumeEnabled = audEn.AsBool();
        else
            FadeAudioVolumeEnabled = true;

        if (data.TryGetValue("FadeVideoOpacityEnabled", out var vidEn))
            FadeVideoOpacityEnabled = vidEn.AsBool();
        else
            FadeVideoOpacityEnabled = true;

        // Prefer explicit FadeProperty; migrate legacy dual-enable when missing.
        if (data.TryGetValue("FadeProperty", out var fadePropVal))
        {
            FadeProperty = (ControlFadeProperty)fadePropVal.AsInt32();
        }
        else
        {
            // Old saves could enable volume and/or opacity together — pick one primary.
            if (FadeVideoOpacityEnabled && !FadeAudioVolumeEnabled)
                FadeProperty = ControlFadeProperty.Opacity;
            else
                FadeProperty = ControlFadeProperty.Volume;
        }

        // Keep legacy flags aligned with the single property.
        FadeAudioVolumeEnabled = FadeProperty == ControlFadeProperty.Volume;
        FadeVideoOpacityEnabled = FadeProperty == ControlFadeProperty.Opacity;

        if (data.TryGetValue("FadeAudioDb", out var audDb))
            FadeAudioDb = audDb.AsSingle();
        else
            FadeAudioDb = 0f;

        if (data.TryGetValue("FadeOpacityPercent", out var opPct))
            FadeOpacityPercent = opPct.AsSingle();
        else
            FadeOpacityPercent = 100f;

        if (data.TryGetValue("FadePan", out var fadePanVal))
            FadePan = Mathf.Clamp(fadePanVal.AsSingle(), -2f, 2f); // allow relative beyond ±1
        else
            FadePan = 0f;

        if (data.TryGetValue("FadeMatrixInputIndex", out var matInVal))
            FadeMatrixInputIndex = Math.Max(0, matInVal.AsInt32());
        else
            FadeMatrixInputIndex = 0;

        if (data.TryGetValue("FadeMatrixOutputIndex", out var matOutVal))
            FadeMatrixOutputIndex = Math.Max(0, matOutVal.AsInt32());
        else
            FadeMatrixOutputIndex = 0;

        FadeMatrixCellTargets = new System.Collections.Generic.Dictionary<int, float>();
        if (data.TryGetValue("FadeMatrixCells", out var cellsVal) &&
            cellsVal.VariantType == Variant.Type.Array)
        {
            foreach (var item in cellsVal.AsGodotArray())
            {
                if (item.VariantType != Variant.Type.Dictionary) continue;
                var cell = item.AsGodotDictionary();
                if (!cell.TryGetValue("In", out var inV) || !cell.TryGetValue("Out", out var outV))
                    continue;
                int inIdx = Math.Max(0, inV.AsInt32());
                int outIdx = Math.Max(0, outV.AsInt32());
                float db = cell.TryGetValue("Db", out var dbV) ? dbV.AsSingle() : 0f;
                FadeMatrixCellTargets[PackMatrixCellKey(inIdx, outIdx)] = db;
            }
        }
        else if (FadeProperty == ControlFadeProperty.RoutingMatrix)
        {
            // Legacy single-cell matrix fade → one multi-cell entry.
            FadeMatrixCellTargets[PackMatrixCellKey(FadeMatrixInputIndex, FadeMatrixOutputIndex)] =
                FadeAudioDb;
        }

        if (data.TryGetValue("SeekMode", out var seekModeVal))
            SeekMode = (ControlFadeMode)seekModeVal.AsInt32();
        else
            SeekMode = ControlFadeMode.Absolute;

        if (data.TryGetValue("SeekTimeSeconds", out var seekTimeVal))
            SeekTimeSeconds = seekTimeVal.AsDouble();
        else
            SeekTimeSeconds = 0;

        if (data.TryGetValue("TargetLayerId", out var layerIdVal))
            TargetLayerId = layerIdVal.AsInt32();
        else
            TargetLayerId = -1;

        if (data.TryGetValue("TranslateMode", out var trModeVal))
            TranslateMode = (ControlFadeMode)trModeVal.AsInt32();
        else
            TranslateMode = ControlFadeMode.Absolute;

        if (data.TryGetValue("TranslateDuration", out var trDurVal))
            TranslateDuration = Math.Max(0.0, trDurVal.AsDouble());
        else
            TranslateDuration = 0;

        if (data.TryGetValue("TranslateSizeEnabled", out var trSzEn))
            TranslateSizeEnabled = trSzEn.AsBool();
        else
            TranslateSizeEnabled = true;

        if (data.TryGetValue("TranslatePositionEnabled", out var trPosEn))
            TranslatePositionEnabled = trPosEn.AsBool();
        else
            TranslatePositionEnabled = true;

        if (data.TryGetValue("TranslateSizeX", out var trSx))
            TranslateSizeX = trSx.AsInt32();
        if (data.TryGetValue("TranslateSizeY", out var trSy))
            TranslateSizeY = trSy.AsInt32();
        if (data.TryGetValue("TranslatePosX", out var trPx))
            TranslatePosX = trPx.AsInt32();
        if (data.TryGetValue("TranslatePosY", out var trPy))
            TranslatePosY = trPy.AsInt32();
    }
}
